### ISSUE TITLE
Отсутствует расчёт остатка кредитного лимита.

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/javaqa-team-diplom#14]
# Описание
При покупке товара на свои + кредитные деньги, должно считаться, какой кредитный лимит остался.

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/javaqa-team-diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать тест со значениями конструктора:

```
initialBalance = 5_000,
creditLimit = 4_000,
rate =  15
```
3. Вызвать в тесте метод расчёта остатка, например он будет называться `creditBalance`, cо значением 6_000
4. Запустить тест
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Остаток на кредитном счёте - 3_000
*Фактический результат:* метод отсутствует

# Скриншот
![image](https://github.com/Alexnoh87/javaqa-team-diplom/assets/128059717/153f8180-8408-4a97-9d23-3f32aa9c3c9a)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
Александр, не совсем понял, зачем этот метод,
где-то в требованиях прописано?
сколько осталось кредитных средств можно и так в любой момент рассчитать так: creditLimit + balance

**Comment by Alexnoh87** [comment]
> Александр, не совсем понял, зачем этот метод,
> где-то в требованиях прописано?
> сколько осталось кредитных средств можно и так в любой момент рассчитать так: creditLimit + balance

creditLimit + balance, так ты посчитаешь общий лимит. А вот если ты у тебя баланс 5 и кредит 5, и ты сделал покупку на 7, т.е взял из кредита 2 тыс, у тебя на балансе стало минус 2000, а кредитный лимит остался ещё 3 тыс, вот его то я и решил потестить. Сделал эти тесты, чтобы полностью покрыть код CreditAccount, без нет метод, в самом низу, getCreditLimit тогда не используется, ну и, нам в задании же дано, что некоторые методы отсутствуют, я посчитал, что это он и есть. Думаешь не нужен этот расчёт?

**Comment by Ramzesito** [comment]
закрыто без реализации, если потребуется после согласования с заказчиком - откроем заново
