### ISSUE TITLE
Не верный расчет итогового баланса при покупке на весь лимит средств. 

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/javaqa-team-diplom#16]
# Описание
При покупке на весь лимит средств баланс + кредитный счет (initialBalance + creditLimit) не верно рассчитывается итоговая сумма на счёте (задолженность).

# Локация дефекта
https://github.com/Alexnoh87/javaqa-team-diplom/blob/f048cf326ae8b7da9cb0a7f5382d65fbd434023c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L55
# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/javaqa-team-diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать тест со значениями конструктора:

```
initialBalance = 5_000,
creditLimit = 5_000,
rate =  15
```
3. Вызвать в тесте метод `pay` cо значением 10_000
4. Запустить тест
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс счёта равен -5_000 
*Фактический результат:* Баланс счёта равен 5_000

# Скриншот
![image](https://github.com/Alexnoh87/javaqa-team-diplom/assets/128059717/32ba3169-2451-429d-ad66-b7aba0838ae3)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
исправлено

**Comment by Ramzesito** [comment]
исправлено, теперь залил на гитхаб изменения
