### ISSUE TITLE
Не верно выполняются техусловия на отрицательный баланс, не превышающий кредитный лимит.

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/javaqa-team-diplom#17]
# Описание
При отрицательном балансе, в рамках кредитного лимита, сразу выкидывается исключение вида IllegalArgumentException, что противоречит условиям программы.
https://github.com/Alexnoh87/javaqa-team-diplom/blob/f048cf326ae8b7da9cb0a7f5382d65fbd434023c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L5

# Локация дефекта
https://github.com/Alexnoh87/javaqa-team-diplom/blob/f048cf326ae8b7da9cb0a7f5382d65fbd434023c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L21

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/javaqa-team-diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать тест на исключения со значениями конструктора:

```
initialBalance = -200,
creditLimit = 5_000,
rate =  15
```
3. Запустить тест, актуальные значения взять из метода `yearChange`
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Сумма процентов -30
*Фактический результат:* Выкидывается исключение вида IllegalArgumentException

# Скриншот
![image](https://github.com/Alexnoh87/javaqa-team-diplom/assets/128059717/15e4eae6-b4cc-4958-978f-dd9d0491b51e)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
да, баланс может стать с течением времени отрицательным, 
но по условиям создания объекта сразу в минус проинициализировать нельзя
```
/**
     * Создаёт новый объект кредитного счёта с заданными параметрами.
     * Если параметры некорректны (кредитный лимит отрицательный и так далее), то
     * должно выкидываться исключения вида IllegalArgumentException.
     *
     * @param initialBalance - неотрицательное число, начальный баланс для счёта
     * @param creditLimit    - неотрицательное число, максимальная сумма которую можно задолжать банку
     * @param rate           - неотрицательное число, ставка кредитования для расчёта долга за отрицательный баланс
```

**Comment by Alexnoh87** [comment]
В техусловиях значит есть ошибка, а точнее немного противоречат друг другу. Баланс может быть минус, но не меньше кредитного лимита. Расчёт процентов делается именно на отрицательный баланс.
https://github.com/Alexnoh87/javaqa-team-diplom/blob/ac3106e29a7b0d07056648b3e9eb3bf7fd0fa4ca/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L5
https://github.com/Alexnoh87/javaqa-team-diplom/blob/ac3106e29a7b0d07056648b3e9eb3bf7fd0fa4ca/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L76
https://github.com/Alexnoh87/javaqa-team-diplom/blob/ac3106e29a7b0d07056648b3e9eb3bf7fd0fa4ca/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L79

**Comment by Ramzesito** [comment]
`* Может иметь баланс вплоть до отрицательного, но до указанного кредитного лимита. `

тут не сказано же, как именно отрицательность может достигаться,

далее уже конкретизируется - в конструкторе не может,
а в процессе траты денег - может

**Comment by Alexnoh87** [comment]
Ошибка в тестах, репорт закрыт
