### ISSUE TITLE
Не вызывается исключение IllegalArgumentException при изменение процентной ставки на отрицательную через сеттер в раннее созданном объекте

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/javaqa-team-diplom#18]
# Описание
При изменении ставки кредитования для расчёта долга на отрицательное значение через сеттер в ранее уже созданном корректном объекте не вызывается исключение IllegalArgumentException. Метод с данными условиями отсутствует.

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/javaqa-team-diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать тест на исключения с корректными значениями конструктора:

```
initialBalance = 5_000,
creditLimit = 5_000,
rate =  15
```
3. Вызвать в тесте метод `setRate` cо значением -15
4. Запустить тест
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Выкидывается исключение вида IllegalArgumentException, программа удачно завершается.
*Фактический результат:* Программа завершается с ошибкой.

# Скриншот
![image](https://github.com/Alexnoh87/javaqa-team-diplom/assets/128059717/cb46f77f-c29e-4b22-8a20-a4d1a591b089)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
исправлено
