### ISSUE TITLE
Не верный расчет общего баланса при пополнении.

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/javaqa-team-diplom#7]
# Описание
При пополнении суммы больше нуля, если на счету уже есть некая сумма, то не верно рассчитывается общий баланс. Сумма на счету не берется во внимание.

# Локация дефекта
https://github.com/Alexnoh87/javaqa-team-diplom/blob/3c00f7081d027417771b15f7c1c6f73439c6b93f/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L66-L70

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/javaqa-team-diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать тест со значениями конструктора:

```
initialBalance = 1_000,
creditLimit = 5_000,
rate =  15
```
4. Вызвать в тесте метод `add` cо значением 1_000
5. Запустить тест
6. Посмотреть на вывод в консоли

*Ожидаемый результат:* Баланс счёта равен 2_000
*Фактический результат:* Баланс счёта равен 1_000

# Скриншот
![image](https://github.com/Alexnoh87/javaqa-team-diplom/assets/128059717/3806cd02-fb23-4b40-b748-c43c0d512877)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
исправлено
