### ISSUE TITLE
Не выполняются техусловия на отрицательный кредитный лимит

### ISSUE THREAD

**Issue by Alexnoh87** [Alexnoh87/javaqa-team-diplom#9]
# Описание
При отрицательном кредитном лимите (creditLimit) не выкидывается исключение вида IllegalArgumentException, отсутствует данный метод.

# Локация дефекта
https://github.com/Alexnoh87/javaqa-team-diplom/blob/3c00f7081d027417771b15f7c1c6f73439c6b93f/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19-L24

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Alexnoh87/javaqa-team-diplom/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать тест на исключения со значениями конструктора:

```
initialBalance = 2_000,
creditLimit = -5_000,
rate =  15
```
4. Запустить тест
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Выкидывается исключение вида IllegalArgumentException, программа удачно завершается.
*Фактический результат:* Программа завершается с ошибкой.

# Скриншот
![image](https://github.com/Alexnoh87/javaqa-team-diplom/assets/128059717/62416910-fc84-492f-876e-e60f93089e93)

# Окружение
* **Операционная система:** Windows 11 Pro 22H2
* **IDE:** IntelliJ IDEA 2023.1 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Ramzesito** [comment]
исправлено
